name: CI - full test suite
on: [pull_request, push]

jobs:
  full_test_suite:
    name: Run full test suite (Rust stable on ubuntu-latest)
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        id: install-rust
        uses: dtolnay/rust-toolchain@stable

      # Cache based on OS/compiler.
      - name: Extract cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            !~/.cargo/registry/index
            !~/.cargo/git/checkouts
            target
            !target/tests
            !target/examples
          key: ${{ runner.os }}-${{ steps.install-rust.outputs.cachekey }}

      - name: Test all crates
        run: cargo test --all --verbose --features "use_serde"

      - name: Test si
        run: cargo test --verbose --no-default-features --features "f32 si"

      - name: Test all non-storage type features
        run: cargo test --verbose --no-default-features --features "autoconvert f32 si use_serde libm"

      - name: Test si with underlying storage types
        run: cargo test --verbose --no-run --no-default-features --features "autoconvert usize isize bigint bigrational complex32 si std use_serde"

      - name: Test all non-si features
        run: cargo test --verbose --no-run --no-default-features --features "autoconvert usize u8 u16 u32 u64 u128 isize i8 i16 i32 i64 i128 bigint biguint rational rational32 rational64 bigrational complex32 complex64 f32 f64 std use_serde"
